Revert "Plang 2153 intermediate file (#70)" (#71)
* Revert "Plang 2153 intermediate file (#70)"

This reverts commit 5a6c9254c4b4a93a38490071892ead088abd02d4.

* Update bitrise.yml

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -6,39 +6,39 @@ app:
   # Shared envs for every test workflow
   - BITRISEIO_FINISHED_STAGES: |-
         [{
-            "id": "449d4000-dfb7-4673-8de2-51189af8866f",
-            "name": "stage-1-new",
+            "id": "fb96d509-3966-4ca7-acf2-da596cb4a895",
+            "name": "stage-1",
             "workflows": [{
-                "external_id": "6f49f5e2-e498-4088-a139-92e109da7abc",
-                "finished_at": "2022-07-27T22:29:11Z",
-                "id": "da8f2e61-d128-4242-be2c-73954055c559",
+                "external_id": "70bbdfd1-96d5-447c-9731-20da9312643c",
+                "finished_at": "2022-05-24T20:39:06Z",
+                "id": "44b69b43-3a3e-474b-a133-99717c96d719",
                 "name": "placeholder",
-                "started_at": "2022-07-27T22:29:10Z",
+                "started_at": "2022-05-24T20:39:04Z",
                 "status": "succeeded"
             }, {
-                "external_id": "825664aa-3ec9-4a75-8c02-33459f82a232",
-                "finished_at": "2022-07-27T22:29:21Z",
-                "id": "cd73e2c0-787a-4a6c-b55c-35ce567184ea",
-                "name": "textfile_generator-new",
-                "started_at": "2022-07-27T22:29:09Z",
+                "external_id": "3daa3d92-6d7a-4791-928a-b83506881ecd",
+                "finished_at": "2022-05-24T20:38:33Z",
+                "id": "5b8e99f4-5836-4eb5-bbc3-61fff4410919",
+                "name": "textfile_generator",
+                "started_at": "2022-05-24T20:38:09Z",
                 "status": "succeeded"
             }]
         }, {
-            "id": "83ebb220-e3e1-4f31-955e-363227bf0765",
-            "name": "stage-2-new",
+            "id": "e9ab9871-3a50-47d0-88f7-33dbceff7e87",
+            "name": "stage-2",
             "workflows": [{
-                "external_id": "323aab5c-39b4-4cd5-974e-7fddf47ce65e",
-                "finished_at": "2022-07-27T22:30:10Z",
-                "id": "e5b0e93c-e139-48af-8549-72e6a4f3119a",
-                "name": "deployer-new",
-                "started_at": "2022-07-27T22:29:49Z",
+                "external_id": "2f031c63-ed6c-4a26-aff1-57b00ed2f8ba",
+                "finished_at": "2022-05-24T20:41:26Z",
+                "id": "f1c01cf2-ebcc-4db6-a19c-dfab20762b06",
+                "name": "deployer",
+                "started_at": "2022-05-24T20:40:47Z",
                 "status": "succeeded"
             }, {
-                "external_id": "4cd4b6d5-7147-4315-a9be-4a1f8d4baae8",
-                "finished_at": "2022-07-27T22:30:05Z",
-                "id": "062304f6-5780-41d4-a23e-c64bf18b56d5",
-                "name": "textfile_generator-new",
-                "started_at": "2022-07-27T22:29:53Z",
+                "external_id": "a9d6148e-59e1-417e-99a0-49e5dd014f85",
+                "finished_at": "2022-05-24T20:40:34Z",
+                "id": "1730a356-6a32-4b77-807b-4a6f587fee33",
+                "name": "textfile_generator",
+                "started_at": "2022-05-24T20:40:15Z",
                 "status": "succeeded"
             }]
         }]
@@ -50,7 +50,6 @@ workflows:
   test_download_all_artifacts_of_build:
     before_run:
     - _setup
-    - _cleanup
     steps:
     - path::./:
         title: Execute step
@@ -58,47 +57,145 @@ workflows:
         - verbose: true
         - artifact_sources: .*
         - bitrise_api_base_url: https://api.bitrise.io
-    - git::https://github.com/bitrise-steplib/bitrise-step-check-step-outputs.git@main:
+    - script:
         title: Validate downloaded artifacts
         is_always_run: true
         inputs:
-        - files: |-
-            EXAMPLE_CSV
-            EXPORT_OPTIONS_PLIST
-            TEST_JSON
-            TEXT_FILE_TXT
+        - content: |-
+            #!/usr/bin/env bash
+            set -ex
+
+            IFS='|' read -ra FILES <<< "$BITRISE_ARTIFACT_PATHS"
+            for i in "${FILES[@]}"; do
+              # process "$i"
+              if [ ! -f $i ]; then
+                echo "$i not found"
+                exit 1
+              fi
+            done
+
+            array=( "example.csv" "export_options.plist" "test.json" "xcode-test-results-ios-simple-objc.html" "lipsum.txt" "generated_text_file.txt" "Test.xcresult.zip" "ios-simple-objcTests.ipa" "cat-illustration@3x.png" "xcodebuild-archive.log" "app-release-unsigned.apk")
+            for i in "${array[@]}"
+            do
+              if [[ "$BITRISE_ARTIFACT_PATHS" != *"$i"* ]]; then
+                echo "BITRISE_ARTIFACT_PATHS not contains the $i file"
+                exit 1
+              fi
+            done
 
   test_download_specific_stage_artifacts:
     before_run:
     - _setup
-    - _cleanup
     steps:
     - path::./:
         title: Execute step
         inputs:
         - verbose: true
-        - artifact_sources: stage-1-new\..*
+        - artifact_sources: stage-1\..*
         - bitrise_api_base_url: https://api.bitrise.io
-    - git::https://github.com/bitrise-steplib/bitrise-step-check-step-outputs.git@main:
+    - script:
         title: Validate downloaded artifacts
         is_always_run: true
         inputs:
-        - files: |-
-            TEXT_FILE_TXT
+        - content: |-
+            #!/usr/bin/env bash
+            set -ex
 
-  _cleanup:
+            IFS='|' read -ra FILES <<< "$BITRISE_ARTIFACT_PATHS"
+            for i in "${FILES[@]}"; do
+              # process "$i"
+              if [ ! -f $i ]; then
+                echo "$i not found"
+                exit 1
+              fi
+            done
+
+            fc=$(ls $BITRISE_ARTIFACT_PATHS | wc -l | xargs)
+            if [ $fc -gt 1 ]; then
+              echo "There are more than 1 files"
+              exit 1
+            fi
+
+            if [[ -z "${BITRISE_ARTIFACT_PATHS}" ]]; then
+              echo "Exported BITRISE_ARTIFACT_PATHS output variable does not exist"
+              exit 1
+            fi
+
+            array=( "generated_text_file.txt")
+            for i in "${array[@]}"
+            do
+              if [[ "$BITRISE_ARTIFACT_PATHS" != *"$i"* ]]; then
+                echo "BITRISE_ARTIFACT_PATHS not contains the $i file"
+                exit 1
+              fi
+            done
+
+  test_export_output_variables_based_on_patterns:
+    before_run:
+    - _setup
     steps:
+    - path::./:
+        title: Execute step
+        inputs:
+        - verbose: true
+        - artifact_sources: .*
+        - export_map: |-
+              TXT_FILES: .*\.txt
+              APK_FILES: .*\.apk
+        - bitrise_api_base_url: https://api.bitrise.io
     - script:
-        title: Get access token
+        title: Validate downloaded artifacts
+        is_always_run: true
         inputs:
         - content: |-
-            #!/bin/env bash
+            #!/usr/bin/env bash
             set -ex
-            envman unset --key EXAMPLE_CSV
-            envman unset --key EXPORT_OPTIONS_PLIST
-            envman unset --key TEST_JSON
-            envman unset --key TEXT_FILE_TXT
 
+            if [[ -z "${TXT_FILES}" ]]; then
+                echo "Exported $TXT_FILES output variable does not exist"
+                exit 1
+            fi
+
+            if [[ -z "${APK_FILES}" ]]; then
+                echo "Exported $APK_FILES output variable does not exist"
+                exit 1
+            fi
+
+            IFS='|' read -ra FILES <<< "$TXT_FILES"
+            for i in "${FILES[@]}"; do
+                # process "$i"
+                if [ ! -f $i ]; then
+                    echo "$i not found"
+                    exit 1
+                fi
+            done
+
+            IFS='|' read -ra FILES <<< "$APK_FILES"
+            for i in "${FILES[@]}"; do
+                # process "$i"
+                if [ ! -f $i ]; then
+                    echo "$i not found"
+                    exit 1
+                fi
+            done
+
+            array=( "lipsum.txt" "generated_text_file.txt" )
+            for i in "${array[@]}"
+            do
+                if [[ "$TXT_FILES" != *"$i"* ]]; then
+                    echo "$TXT_FILES not contains the $i file"
+                    exit 1
+                fi
+            done
+
+            array=( "app-release-unsigned.apk" )
+            for i in "${array[@]}"
+            do
+              if [[ "$APK_FILES" != *"$i"* ]]; then
+                  echo "$APK_FILES not contains the $i file"
+                  exit 1
+              fi
+            done
   _setup:
     steps:
     - script:
@@ -113,7 +210,7 @@ workflows:
                 --data "client_secret=$BITRISE_AUTH_SERVICE_ARTIFACT_PULL_CLIENT_SECRET" \
                 --data "grant_type=urn:ietf:params:oauth:grant-type:uma-ticket" \
                 --data "scope=build_artifact:read build:read app:read" \
-                --data "claim_token=ewogICJidWlsZF9pZHMiOiBbCiAgICAiNmY0OWY1ZTItZTQ5OC00MDg4LWExMzktOTJlMTA5ZGE3YWJjIiwKICAgICI4MjU2NjRhYS0zZWM5LTRhNzUtOGMwMi0zMzQ1OWY4MmEyMzIiLAogICAgIjMyM2FhYjVjLTM5YjQtNGNkNS05NzRlLTdmZGRmNDdjZTY1ZSIsCiAgICAiNGNkNGI2ZDUtNzE0Ny00MzE1LWE5YmUtNGExZjhkNGJhYWU4IgogIF0sCiAgInBpcGVsaW5lX2lkIjogWwogICAgImMyMGEwNmM1LWRjYmUtNDMyYy04MjYxLTYzMzc4OWIwNzQwNiIKICBdCn0=" \
+                --data "claim_token=ewogICJidWlsZF9pZHMiOiBbCiAgICAiNzBiYmRmZDEtOTZkNS00NDdjLTk3MzEtMjBkYTkzMTI2NDNjIiwKICAgICIzZGFhM2Q5Mi02ZDdhLTQ3OTEtOTI4YS1iODM1MDY4ODFlY2QiLAogICAgIjJmMDMxYzYzLWVkNmMtNGEyNi1hZmYxLTU3YjAwZWQyZjhiYSIsCiAgICAiYTlkNjE0OGUtNTllMS00MTdlLTk5YTAtNDllNWRkMDE0Zjg1IgogIF0sCiAgInBpcGVsaW5lX2lkIjogWwogICAgImIzY2U4MGJhLTEzOGMtNDk4Mi1iMmRmLWM4NGIzMzhiM2EyZSIKICBdCn0=" \
                 --data "claim_token_format=urn:ietf:params:oauth:token-type:jwt" \
                 --data "audience=bitrise-api")
 
