Use temp dir and refactor the test cases

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -30,24 +30,16 @@ workflows:
             #!/usr/bin/env bash
             set -ex
 
-            if [ ! -f ./_tmp/app-release-unsigned.apk ]; then
-              echo "app-release-unsigned.apk not found"
-              exit 1
-            fi
-            if [ ! -f ./_tmp/cat-illustration@3x.png ]; then
-              echo "cat-illustration@3x.png not found"
-              exit 1
-            fi
-            if [ ! -f ./_tmp/Test.xcresult.zip ]; then
-              echo "Test.xcresult.zip not found"
-              exit 1
-            fi
-            if [[ -z "${PULLED_ARTIFACT_LOCATIONS}" ]]; then
-              echo "Exported PULLED_ARTIFACT_LOCATIONS output variable does not exist"
-              exit 1
-            fi
+            IFS=',' read -ra FILES <<< "$PULLED_ARTIFACT_LOCATIONS"
+            for i in "${FILES[@]}"; do
+              # process "$i"
+              if [ ! -f $i ]; then
+                echo "$i not found"
+                exit 1
+              fi
+            done
 
-            array=( "_tmp/example.csv" "_tmp/export_options.plist" "_tmp/test.json" "_tmp/xcode-test-results-ios-simple-objc.html" "_tmp/lipsum.txt" "_tmp/generated_text_file.txt" "_tmp/Test.xcresult.zip" "_tmp/ios-simple-objcTests.ipa" "_tmp/cat-illustration@3x.png" "_tmp/xcodebuild-archive.log" "_tmp/app-release-unsigned.apk")
+            array=( "example.csv" "export_options.plist" "test.json" "xcode-test-results-ios-simple-objc.html" "lipsum.txt" "generated_text_file.txt" "Test.xcresult.zip" "ios-simple-objcTests.ipa" "cat-illustration@3x.png" "xcodebuild-archive.log" "app-release-unsigned.apk")
             for i in "${array[@]}"
             do
               if [[ "$PULLED_ARTIFACT_LOCATIONS" != *"$i"* ]]; then
@@ -74,11 +66,17 @@ workflows:
         - content: |-
             #!/usr/bin/env bash
             set -ex
-            if [ ! -f ./_tmp/generated_text_file.txt ]; then
-              echo "generated_text_file.txt not found"
-              exit 1
-            fi
-            fc=$(ls ./_tmp | wc -l | xargs)
+
+            IFS=',' read -ra FILES <<< "$PULLED_ARTIFACT_LOCATIONS"
+            for i in "${FILES[@]}"; do
+              # process "$i"
+              if [ ! -f $i ]; then
+                echo "$i not found"
+                exit 1
+              fi
+            done
+
+            fc=$(ls $PULLED_ARTIFACT_LOCATIONS | wc -l | xargs)
             if [ $fc -gt 1 ]; then
               echo "There are more than 1 files"
               exit 1
@@ -89,7 +87,7 @@ workflows:
               exit 1
             fi
 
-            array=( "_tmp/generated_text_file.txt")
+            array=( "generated_text_file.txt")
             for i in "${array[@]}"
             do
               if [[ "$PULLED_ARTIFACT_LOCATIONS" != *"$i"* ]]; then
