e2e check

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -9,32 +9,43 @@ app:
 
 workflows:
 
-  test_something:
+  test_pull_single_artifact:
     before_run:
     - _setup
-    steps:
-
-
-  test_another_thing:
-    before_run:
-    - _setup
-    steps:
+    after_run:
+    - _check_downloaded_artifacts
+    steps:  
 
   _setup:
     steps:
     - script:
-        title: Remove _tmp folder
+        title: Clean _tmp folder
         inputs:
         - content: |-
             #!/bin/env bash
             set -ex
             rm -rf ./_tmp
-#    - git::https://github.com/bitrise-steplib/bitrise-step-simple-git-clone.git@master:
-#        title: Clone sample app
-#        inputs:
-#        - repository_url: $TEST_APP_URL
-#        - branch: $TEST_APP_BRANCH
-#        - clone_into_dir: ./_tmp
+    - change-workdir:
+        title: Switch working dir to _tmp
+        run_if: "true"
+        inputs:
+        - path: ./_tmp
+        - is_create_path: true
     - path::./:
         title: Execute step
         inputs:
+
+  _check_downloaded_artifacts:
+    steps:
+    - script:
+        title: Validate downloaded artifacts
+        is_always_run: true
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash             
+            set -ex
+            if [ ! -f ./Artifact.zip ]; then
+              echo "Artifact.zip not found"
+              exit 1
+            fi
+
